---
title: "Aggregate and Process DE Results"
author: "Zhaoheng Li, Wei Sun"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    highlight: tango
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
    number_sections: false
  df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,warning = F, message= F}
 library(Seurat)
library(ggpubr)
library(viridis)
library(tidyr)
library(dplyr)
library(tidyr)
library(readxl)
library(stringr)
library(gridExtra)
library(grid)
library(purrr)
library(tidyverse)
out_dir = "/fh/fast/sun_w/zhaoheng_li/MSK_DEC24/Analysis/outs/differential_expression"
```


# save DESeq2 results to tsv files by genotypes

```{r}
res_list = list()
for (tp in c("D-1", "D3", "D7", "D11", "D18")) {
  res <- readRDS(file.path(out_dir, paste0("DE_pseudobulk_", tp, ".RDS")))
  res$tp = tp
  res_list[[tp]] = res
}
res_all = Reduce(rbind,res_list)

res_list =  split(res_all, res_all$genotype) # split by genotype

for(geno in names(res_list)){
    write.table(
    res_list[[geno]],
    file      = file.path(out_dir, paste0("genotype_DEGs/", gsub("/","_",geno), ".tsv")),
    sep       = "\t",
    quote     = FALSE,
    row.names = FALSE,
    col.names = TRUE
  )
}
```

# Session information

```{r}
gc()
sessionInfo()
```
