---
title: "Number of DE Genes (Cell-Level Test)"
author: "Zhaoheng Li, Wei Sun"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal
    highlight: tango
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: false
    number_sections: false
  df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,warning = F, message= F}
 library(Seurat)
library(ggpubr)
library(viridis)
library(tidyr)
library(dplyr)
library(tidyr)
library(readxl)
library(stringr)
library(gridExtra)
library(grid)
library(purrr)
library(tidyverse)
out_dir = "/fh/fast/sun_w/zhaoheng_li/MSK_DEC24/Analysis/outs/differential_expression"
celllevel_out_dir = file.path(out_dir,"cell-level")
```



# barplots

```{r barplot,fig.width=8,fig.height=6}

for( tp in c("D-1","D3","D7","D11","D18")){
  print(tp)
  res = read.csv(file.path(celllevel_out_dir,paste0("DE_cell-level_",tp,".csv")),row.names = 1)
  fig = res%>%
   dplyr::filter(p_val_adj<0.05)%>%
      group_by(celltype,genotype)%>%
   dplyr::summarise(n_DEG = n_distinct(gene))%>%
    ggplot(aes(x=genotype,y=n_DEG))+
    geom_col()+
    xlab("")+
    ylab("Number of DE Genes")+
    theme_classic()+
    theme(text = element_text(size = 5),
            axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))+
    facet_wrap(~celltype)
  ggsave(file.path(celllevel_out_dir,paste0("nDEGs/",tp,"_nDEG.png",sep='')),fig,width = 8,height = 6)
  print(fig)
}
```



```{r,fig.width=8,fig.height=6}

nDEG = list()
for( tp in c("D-1","D3","D7","D11","D18")){
  print(tp)
  res = read.csv(file.path(celllevel_out_dir,paste0("DE_cell-level_",tp,".csv")),row.names = 1)
  res$gene = rownames(res)
  df = res%>%
   dplyr::filter(p_val_adj<0.05)%>%
      group_by(celltype,genotype)%>%
   dplyr::summarise(n_DEG = n_distinct(gene))
  df$tp = tp
  nDEG[[tp]] = df
}
nDEG_df = Reduce(rbind, nDEG)

nDEG_df = nDEG_df %>% 
  mutate(
    id        = paste(tp, celltype, sep = "_"),
    log_nDEG  = log10(n_DEG + 1)
  )

nDEG_df$id = fct_inorder(nDEG_df$id)
head(nDEG_df)
```



# dotplot

```{r,fig.height=6,fig.width=6}
id_levels = levels(nDEG_df$id)      
df = nDEG_df %>%
  filter(tp != "D-1") %>%                    
  mutate(id = factor(id, levels = id_levels)) %>% 
  droplevels()                                    

dotplot = df %>% ggplot(aes(x = id, y = genotype,
           size  = log_nDEG,
           colour = log_nDEG)) +
  geom_point(alpha = 0.85) +
  scale_size(range = c(0.8, 5), name = "log10(#DEG + 1)") +
  scale_colour_gradient(
    low  = "white",
    high = "red",
    name = "log10(#DEG + 1)"
  )+
  scale_x_discrete(limits = levels(df$id)) +
  labs(x = NULL, y = "KO genotype") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
    legend.position = "right"
  )
dotplot
ggsave(file.path(celllevel_out_dir,"nDEGs/nDEGs_dotplot.png"),dotplot,width = 6,height = 6)
```

```{r}

write.table(
  nDEG_df,
  file      = file.path(celllevel_out_dir,"nDEGs/nDEG.tsv"),
  sep       = "\t",
  quote     = FALSE,
  row.names = FALSE
)
```

# Session information

```{r}
gc()
sessionInfo()
```


